name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Ensure cnpy submodule is initialized if needed

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U pip setuptools wheel build scikit-build twine ninja

    #- name: Build & install
     # run: |
        # Clean previous builds
        #rm -rf _skbuild *.egg-info
          
        ## Install with verbose output
        #python -m pip install . -vv

      env:
        CMAKE_GENERATOR: Ninja

    - name: Clean old build artifacts
      run: |
        rm -rf dist
        rm -rf build
        rm -rf *.egg-info

    - name: Build package
      run: python -m build
  
    - name: Check distribution
      run: twine check dist/*
  
    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
