name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive  # If using cnpy as a submodule

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential  # Ensure CMake is available

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine pybind11  # Explicitly install pybind11
        pip install scikit-build ninja  # Required for skbuild

    - name: Clean old build artifacts
      run: |
        rm -rf dist build *.egg-info

    - name: Build package with CMake args
      env:
        CMAKE_ARGS: "-Dpybind11_DIR=$(python -c 'import pybind11; print(pybind11.get_cmake_dir())')"
      run: |
        python -m build --wheel

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}