name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write  # Add package permission to upload to PyPI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Specify a particular Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Clean old build artifacts
      run: |
        rm -rf dist
        rm -rf build
        rm -rf *.egg-info

    - name: Build package
      run: python -m build --wheel

    - name: Check distribution
      run: twine check dist/*

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
