name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel build scikit-build ninja twine cibuildwheel

    - name: Clean old builds
      run: rm -rf dist build *.egg-info _skbuild

    - name: Build package with cibuildwheel
      run: |
        export CIBW_BUILD="cp38-* cp39-* cp310-* cp311-* cp312-*"
        export CIBW_SKIP="*-manylinux_i686 *-musllinux_i686 *-win32"
        # Different package managers and package names for different platforms
        export CIBW_BEFORE_BUILD_MANYLINUX="yum install -y openmpi-devel && pip install ninja"
        export CIBW_BEFORE_BUILD_MUSLLINUX="apk add openmpi-dev && pip install ninja"
        export CIBW_BEFORE_BUILD_MACOS="brew install open-mpi && pip install ninja"
        export CIBW_ENVIRONMENT="CMAKE_ARGS='-DMPI_HOME=/usr/lib64/openmpi'"
        python -m cibuildwheel --output-dir dist

    - name: Check distribution
      run: twine check dist/*

    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}